name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Upgrade pip
        run: |
          # install pip=>20.1 to use "pip cache dir"
          python3 -m pip install --upgrade pip
      - name: Install black, flake8 and isort
        run: |
          python3 -m pip install black, flake8 isort
      - name: Lint Python
        run: |
          black --check $locations
          flake8 $locations
          isort --check $locations
        env:
          locations: "mordle tests noxfile.py"
